# Generated by Django 3.0.7 on 2021-05-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.AddField(
            model_name='bookings',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.Customers'),
        ),
        migrations.AddField(
            model_name='journeystage',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='airbag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='cdplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='centrallock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='powerdoorlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='powersteering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='powerwindows',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
