# Generated by Django 3.0.7 on 2021-05-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20210523_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='carvariant',
            old_name='dayprice',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='carvariant',
            name='kmprice',
        ),
    ]
