# Generated by Django 3.0.7 on 2021-05-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20210523_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rcno',
        ),
    ]
