# Generated by Django 3.0.7 on 2021-05-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_remove_car_rcno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='role',
        ),
    ]
