# Generated by Django 3.0.7 on 2021-05-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_car_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='mstatus',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
