# Generated by Django 3.0.7 on 2021-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_auto_20210530_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
