# Generated by Django 3.0.7 on 2021-05-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_drivers_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='chargetype',
        ),
    ]
