# Generated by Django 3.0.7 on 2021-05-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0010_auto_20210530_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.CarVariant'),
        ),
    ]
