# Generated by Django 3.0.7 on 2021-05-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0011_bookings_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nameoncard',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
