# Generated by Django 3.0.7 on 2021-05-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0014_payment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymentmethod',
        ),
    ]
